### ISSUE TITLE
FFC cofs branch (parallel compilation bug)

### ISSUE THREAD

**Issue by tkarna** [tkarna/cofs#4]
The cofs FFC branch is currently identical to fd_bendy which is somewhat outdated. For example it predates this fix for parallel compilation:
https://bitbucket.org/mapdes/ffc/pull-requests/79/sort-entry-ir-to-ensure-deterministic/diff

We could cherry-pick the fix or rebase cofs branch on a newer version of master. I'd go for the latter but to me it's unclear what is the latest bendy compatible commit in FFC.

**Comment by wence-** [comment]
I tried moving the branch forward, but got lost in a sequence of problems.  So I've cherry-picked that one commit and updated the branch.

**Comment by wence-** [comment]
I've made the short-term minimal fix.  Hopefully ffc will go away in the slightly longer term.
