### ISSUE TITLE
Travis fails with "No module named scipy"

### ISSUE THREAD

**Issue by tkarna** [tkarna/cofs#7]
In #6 travis dies with
```
==================================== ERRORS ====================================
__________ ERROR collecting test/continuity3d/test_continuity_mes.py ___________
test/continuity3d/test_continuity_mes.py:8: in <module>
    from scipy import stats
E   ImportError: No module named scipy
__________ ERROR collecting test/swe2d/test_steady_state_basin_mms.py __________
test/swe2d/test_steady_state_basin_mms.py:15: in <module>
    from scipy import stats
E   ImportError: No module named scipy
__________ ERROR collecting test/tracerEq/test_steady_adv-diff_mms.py __________
test/tracerEq/test_steady_adv-diff_mms.py:8: in <module>
    from scipy import stats
E   ImportError: No module named scipy
=============== 53 passed, 2 skipped, 3 error in 988.77 seconds ================
The command "py.test --travis -v test" exited with 1.
```
although `python-scipy` is in `.travis.yml`. Any ideas?

**Comment by stephankramer** [comment]
I think it can't find the system installed scipy (from the python-scipy package) within the virtualenv of the firedrake install. I'm guessing add `pip install -U scipy` to `before-install`?

**Comment by tkarna** [comment]
That's probably it. Presumably one could also use the system packages with virtualenv. But this doesn't seem to be an option in `firedrake-install` where it is written
`virtualenv.create_environment("firedrake", site_packages=False)`

I'll try pip installing scipy for now.

**Comment by stephankramer** [comment]
Sorry that was a silly suggestion. The pip installs in the `before_install` are only the requirements for the firedrake install script itself to run. The virtualenv that is used in the tests only exists after the install script is run, so the scipy and numpy requirements should be added to requirements.txt. Not sure what to do about the time-outs, installing scipy takes a while (this does seem to be cached though even between subsequently new virtualenvs).

**Comment by wence-** [comment]
Yes, I cache the firedrake installation so the next time it runs everything is faster. If travis times out installing scipy try installing with -v so that it prints more to the screen

**Comment by tkarna** [comment]
OK. I forgot that firedrake depends on numpy, so I guess we only need to add scipy in requirements. 

I could remove that scipy dependency if it slows down the tests too much. Currently scipy is only used to compute linear regression, which is available in numpy.linalg as well...

**Comment by wence-** [comment]
Given the caching that I do on travis, it'll only slow down the first run of the tests I think

**Comment by tkarna** [comment]
I think this is resolved now in #6 . Out of curiosity, is it possible to remove the cached firedrake installation in travis?

**Comment by wence-** [comment]
Yes, click on settings on the travis page. There's an option to clear caches

**Comment by tkarna** [comment]
Okay good to know.
